name: services_project
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #UX/UI
  google_fonts: ^2.3.3
  flutter_svg: ^1.1.0
  another_flushbar: ^1.10.29
  flutter_native_splash: ^2.2.3
  mask_text_input_formatter: ^2.3.0
  pattern_formatter: ^2.0.0
  intl: ^0.17.0
  timezone: ^0.8.0

  #State Management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3


  #Maps
  google_maps_flutter: ^2.1.5
  geolocator: ^8.2.1

  #firebase
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16

  #maps
  geocoding: ^2.0.4
  
  #http - dio
  dio: ^4.0.6
  shared_preferences: ^2.0.15


  #Usefull tools
  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  progress_indicators: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

#
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/


#splash Config
flutter_native_splash:
  color: "#BE2BFA"
  android_12:
    icon_background_color: "BE2BFA"
    


  # To add assets to your application, add an assets section, like this:
  # assets:
  # - ./assets/images/Group.svg
  # - ./assets/images/background.svg
  # - ./assets/images/splash_background.png
  # - ./assets/images/Splash.png
  # - ./assets/images/event_background.svg
  # - ./assets/images/map.svg
  