// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXnmbla0CeeoTh5MPdh2uT7uGd-lmOI4',
    appId: '1:1070184104025:web:f22a20decf3c081851f148',
    messagingSenderId: '1070184104025',
    projectId: 'bancodedados2-d106e',
    authDomain: 'bancodedados2-d106e.firebaseapp.com',
    databaseURL: 'https://bancodedados2-d106e.firebaseio.com',
    storageBucket: 'bancodedados2-d106e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-AfAvmCsik8SpCC-0yMHHG6hNHsTBSGo',
    appId: '1:1070184104025:android:061887f772e208e851f148',
    messagingSenderId: '1070184104025',
    projectId: 'bancodedados2-d106e',
    databaseURL: 'https://bancodedados2-d106e.firebaseio.com',
    storageBucket: 'bancodedados2-d106e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gR4z-Dx6UdJEapVXKzSyYACjpRxH3u8',
    appId: '1:1070184104025:ios:dd5e4cd68da4260151f148',
    messagingSenderId: '1070184104025',
    projectId: 'bancodedados2-d106e',
    databaseURL: 'https://bancodedados2-d106e.firebaseio.com',
    storageBucket: 'bancodedados2-d106e.appspot.com',
    iosClientId: '1070184104025-8khaa4pglnagspu52ca1g44aia95f9d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.servicesProject',
  );
}
